language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - pypy
services:
  - cassandra
env:
  - TOXENV=`pypy -c 'import sys; print("pypy" if "__pypy__" in sys.builtin_module_names else "".join(map(str, sys.version_info[:2])))'`
install:
  - pip install -U pip wheel setuptools virtualenv
  - virtualenv /tmp/env
  - /tmp/env/bin/pip install tox
script:
  - /tmp/env/bin/tox
