language: python
services:
  - cassandra
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python2.6
      - python2.7
      - python3.3
      - python3.4
      - python3.5
      - python3.6
      - pypy
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=pypy
install:
  - pip install -U pip wheel setuptools virtualenv
  - virtualenv /tmp/env
  - /tmp/env/bin/pip install tox
script:
  - /tmp/env/bin/tox
