language: python
sudo: false
services:
  - cassandra
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python2.7
      - python3.2
      - python3.3
      - python3.4
      - python3.5
      # - python3.6
env:
  - TOXENV=py27
  - TOXENV=py35
cache:
  directories:
    pip: true
install:
  - pip install -U pip
  - pip install -U wheel
  - pip install -U setuptools
  - pip install -U virtualenv
  - virtualenv -p python3.5 /tmp/env
  - /tmp/env/bin/pip install tox
script:
  - /tmp/env/bin/tox
