dist: trusty
language: python
sudo: required

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
env:
  global:
    - CMD_PATT=cassandra
  matrix:
    - CASSANDRA_VERSION=22x
    - CASSANDRA_VERSION=39x

before_install:
  - sudo add-apt-repository -y ppa:webupd8team/java
  - echo "deb http://www.apache.org/dist/cassandra/debian $CASSANDRA_VERSION main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
  - gpg --keyserver pgp.mit.edu --recv-keys F758CE318D77295D
  - gpg --export --armor F758CE318D77295D | sudo apt-key add -
  - gpg --keyserver pgp.mit.edu --recv-keys 2B5C1B00
  - gpg --export --armor 2B5C1B00 | sudo apt-key add -
  - gpg --keyserver pgp.mit.edu --recv-keys 0353B12C
  - gpg --export --armor 0353B12C | sudo apt-key add -
  - sudo apt-get update -y
install:
  - sudo apt-get install -y oracle-java8-set-default
  - java -version
  - sudo apt-get install -y cassandra
before_script:
  - sudo service cassandra start
  - sudo service cassandra status
  - sudo nodetool status
  - /opt/python/2.7/bin/pip install virtualenv
  - /opt/python/2.7/bin/virtualenv env_cqlsh
  - source env_cqlsh/bin/activate
  - travis_retry travis_wait 30 pip install cqlsh

  # - echo 'waiting for cassandra is up'; while ! echo "exit" | cqlsh; do sleep 1; echo -n '.'; done
  - deactivate
script:
  # - export TOXENV=py`python -c 'import sys; print("py" if "__pypy__" in sys.builtin_module_names else "".join(map(str, sys.version_info[:2])))'`
  # - echo "$TOXENV"

  # - tox
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email: false
