language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - pypy
services:
  - cassandra
install:
  - pip install -U pip wheel setuptools virtualenv
  - virtualenv /tmp/env
  - /tmp/env/bin/pip install tox
script:
  - export TOXENV=py`python -c 'import sys; print("py" if "__pypy__" in sys.builtin_module_names else "".join(map(str, sys.version_info[:2])))'`
  - echo "$TOXENV"
  - python --version

  - /tmp/env/bin/tox
