dist: trusty
language: python
sudo: required
python:
  - "3.5"
  - "3.6"
env:
  matrix:
    - CASSANDRA_VERSION=311x CQL_VERSION=3.4.4
before_install:
  - sudo add-apt-repository -y ppa:webupd8team/java
  - echo "deb http://www.apache.org/dist/cassandra/debian $CASSANDRA_VERSION main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
  - echo "deb-src http://www.apache.org/dist/cassandra/debian $CASSANDRA_VERSION main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
  - curl https://www.apache.org/dist/cassandra/KEYS | sudo apt-key add -
  - sudo apt-get update -y
install:
  - sudo apt-get install -y oracle-java8-set-default
  - java -version
  - sudo apt-get install -y cassandra

  - pip install -U setuptools
  - pip install -U pip
  - pip install -U wheel
  - pip install -U tox
before_script:
  - sudo service cassandra start
  - /opt/python/2.7/bin/pip install virtualenv
  - /opt/python/2.7/bin/virtualenv env_cqlsh
  - source env_cqlsh/bin/activate
  - pip install cqlsh
  - echo 'waiting for cassandra is up'; while ! echo "exit" | cqlsh --cqlversion=$CQL_VERSION; do sleep 1; echo -n '.'; done
  - deactivate
script:
  - export TOXENV=py`python -c 'import sys; print("".join(map(str, sys.version_info[:2])))'`
  - echo "$TOXENV"

  - tox
cache: pip
notifications:
  email: false


deploy:
  provider: pypi
  user: hellysmile
  password:
    secure: "EG6ZiN/WbbfObG8+GCFh3e5kzqdcv35gHcP+bJ1GjJL6sw4ohWBYXZCX1mo/ScYNFcVJzR/TxPp1hSKhgBG5m/X/tTm7tvenpq/44B8xTFX4I8G18AW5k7Jj7kR321eXS13txQ/3a43k38icfEzmMKy3U01cOwJE9X9dVq57zZpSpAk3O+eMqAnfvQN620TaxYoBGlQ8jBgwtw8F3IQXStRm1QCIdCpYXttMxTWTPbdDgTnoDiMa76JYuYIaGiOvm544INjrJyXDMQx9bY+jxnV/AcCkSF3FODnoO9DuFU0NdUzQB0gRtGo8ZKeKR1Q1vcufWubnbU3fRvaHUQPXirS3T6yu+GZ5gcwt4s54VPeYShwL55DK0r8h6IQWYr/ZhGUoWVm9adGmnoP1SDycbjsu0Prq8XzQT4BePmto4yNZbTYsgFuLTXFA+AWZ1QL20MPgTM5yqrIbUnG04uGHEWiuZfHnT8kjpJleOFOtCm3WHLJGHyeFHduANLiEPjVwORFqNEXRH/QjFNLkd+Q1EkkusPt/WMCMmz0v2a9lVle/h+3jB3XSP0KN38xNmQDjU4vFR0LURVs4pyKc51EKwhi/3sbMb47SsCwhGyJATg/TgVTTM90/CLq9W3Q7dEy4qPejUI7YD5kixKIBh7w5jB08X26fy98IXYh/KfBmow4="
  distributions: "sdist upload"
  on:
    tags: true
    all_branches: true
    python: 3.5
