language: python
services:
  - cassandra
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python2.7
      - python3.3
      - python3.4
      - python3.5
      # - python3.6
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
cache:
  directories:
    pip: true
install:
  - pip install -U pip wheel setuptools virtualenv
  - virtualenv /tmp/env
  - /tmp/env/bin/pip install tox
script:
  - /tmp/env/bin/tox
