dist: trusty
sudo: required

language: python
python:
- 3.4
- 3.5
- 3.6

cache: pip

addons:
  apt:
    sources:
    - sourceline: 'ppa:webupd8team/java'
    - sourceline: 'deb http://www.apache.org/dist/cassandra/debian 311x main'
      key_url: &apache-key https://www.apache.org/dist/cassandra/KEYS
    - sourceline: 'deb-src http://www.apache.org/dist/cassandra/debian 311x main'
      key_url: *apache-key
    packages:
    - oracle-java8-set-default
    - cassandra
services:
- cassandra

before_install:
- java -version
- python -V
install:
- pip install tox

before_script:
- tox -e wait-for-cassandra
script:
- tox -e python

jobs:
  include:
  - stage: Push to PYPI (runs only for tagged commits)
    if: tag IS present
    python: 3.6
    addons: {}
    services: []
    before_install: []
    install: skip
    before_script: []
    script: skip
    deploy:
      provider: pypi
      user: hellysmile
      password:
        secure: "EG6ZiN/WbbfObG8+GCFh3e5kzqdcv35gHcP+bJ1GjJL6sw4ohWBYXZCX1mo/ScYNFcVJzR/TxPp1hSKhgBG5m/X/tTm7tvenpq/44B8xTFX4I8G18AW5k7Jj7kR321eXS13txQ/3a43k38icfEzmMKy3U01cOwJE9X9dVq57zZpSpAk3O+eMqAnfvQN620TaxYoBGlQ8jBgwtw8F3IQXStRm1QCIdCpYXttMxTWTPbdDgTnoDiMa76JYuYIaGiOvm544INjrJyXDMQx9bY+jxnV/AcCkSF3FODnoO9DuFU0NdUzQB0gRtGo8ZKeKR1Q1vcufWubnbU3fRvaHUQPXirS3T6yu+GZ5gcwt4s54VPeYShwL55DK0r8h6IQWYr/ZhGUoWVm9adGmnoP1SDycbjsu0Prq8XzQT4BePmto4yNZbTYsgFuLTXFA+AWZ1QL20MPgTM5yqrIbUnG04uGHEWiuZfHnT8kjpJleOFOtCm3WHLJGHyeFHduANLiEPjVwORFqNEXRH/QjFNLkd+Q1EkkusPt/WMCMmz0v2a9lVle/h+3jB3XSP0KN38xNmQDjU4vFR0LURVs4pyKc51EKwhi/3sbMb47SsCwhGyJATg/TgVTTM90/CLq9W3Q7dEy4qPejUI7YD5kixKIBh7w5jB08X26fy98IXYh/KfBmow4="
      distributions: sdist bdist_wheel
      on:
        tags: true
        all_branches: true

notifications:
  email: false
