dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - pypy
services:
  - cassandra
script:
  - export TOXENV=py`python -c 'import sys; print("py" if "__pypy__" in sys.builtin_module_names else "".join(map(str, sys.version_info[:2])))'`
  - echo "$TOXENV"
  - python --version

  - tox
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email: false
