language: python
python:
  - python2.6
  - python2.7
  - python3.3
  - python3.4
  - python3.5
  - python3.6
  - nightly
  - pypy
services:
  - cassandra
env:
  - TOXENV=`python -c 'import sys; print("".join(map(str, sys.version_info[:2])))'`
install:
  - pip install -U pip wheel setuptools virtualenv
  - virtualenv /tmp/env
  - /tmp/env/bin/pip install tox
script:
  - /tmp/env/bin/tox
